config/routes.rb
  Rails.application.routes.draw do
    devise_for :users, controllers: { confirmations: 'users/confirmations' }
    resources :posts do
      resources :comments
    end

    root "home#root"
    get '/comments/:id/edit', to: 'comments#edit', as: :edit_comment
    put '/comments/:id/edit', to: 'comments#update', as: :update_comment
    delete '/comments/:id/destroy', to: 'comments#destroy', as: :destroy_comment


  # manual setup
    devise_scope :user do
      # Redirests signing out users back to sign-in
      get "users" => "devise/sessions#new"
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :comments, dependent: :destroy 
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ create update ]
  before_action :set_current_comment, only: %i[ edit update show destroy ]
  def index
    @comment = Comment.all
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def show
    # @commnet_current_user = Comment.joins(:post).where(:posts => { :user_id => @user.id })
    # @comment_current_post = Comment.joins(:post)
  end

  def create
    @comment = Comment.new(set_comment.merge(post_id: params[:post_id],user_id: current_user.id))
    if @comment.save
      redirect_to post_url(@comment)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    @comment.update(set_comment)
    redirect_to post_path(@comment.post_id)
  end

  private
  def set_current_comment
    @comment = Comment.find(params[:id])
  end
  def set_comment
    params.require(:comment).permit(:comment_body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def root
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ create update ]
  before_action :set_current_post, only: %i[ edit update show destroy ]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post_last =Post.last
    @post_by_id = Post.order(:id)
    # @post_by_created_at = Post.sort_by(&:created_at)
    # @comment = @post.comments.build

    @comment = Comment.new
  end

  def create
    @post = Post.new(set_post.merge(user_id: current_user.id))
    if @post.save
      redirect_to post_url(@post), notice: 'posts saved'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @post.update(set_post)
      redirect_to @post
    else
      render status: :unprocessable_entity
    end
  end

  private
  def set_current_post
    @post = Post.find(params[:id])
  end
  def set_post
    params.require(:post).permit(:id, :title, :post_body, :source, :resource)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/views/comments/_comment.html.erb
<p>
  <%= comment.comment_body %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, :url => post_comments_path(@post)) do |f| %>
  <%= f.label :comment_body, "comment here" %>
  <%= f.text_area :comment_body, class: "form-control"%>
  <%= f.submit 'Leave Commaent' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing post</h1>

<%= form_with(model: @comment, method: :put, :url => edit_comment_path ) do |f| %>
  <%= f.label :comment_body, "comment here" %>
  <%= f.text_area :comment_body, class: "form-control"%>
  <%= f.submit 'Leave Commaent' %>
<% end %>

app/views/comments/new.html.erb
<h1> comment </h1>
<%= render "form", comment: @comment %>

app/views/home/_header.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a>
      <%= link_to "Blog-App", root_path, class: "navbar-item is-capitalized has-text-weight-semibold" %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Dashboard", posts_path, class: "navbar-item"%>
      <%= link_to "New Articles", new_post_path, class: "navbar-item"%>
      <%= link_to "Preference", edit_user_registration_path, class: "navbar-item"%>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <li class="button is-primary active"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <li class="button is-primary active"><%= link_to "Preference", edit_user_registration_path%></li>
          <% else %>
            <li class="button is-primary active"><%= link_to "Sign up", new_user_registration_path %></li>
            <li class="button is-light active"><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>

app/views/home/root.html.erb
<h1 class="text-3xl font-bold underline">
  you in root file
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header'%>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <section class="hero is-halfheight">
      <div class="hero-body">
        <div class="">
          <p class="subtitle">
            <%#= current_user.id %>
            <%= yield %>
          </p>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this posts from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "control input" %>
  </div>

  <div class="field">
    <%= form.label :post_body, class: "label" %>
    <%= form.text_field :post_body, class: "control textarea" %>
  </div>

  <div class="field">
    <%= form.label :source, class: "label" %>
    <%= form.text_field :source, class: "control input" %>
  </div>

  <div>
    <%= form.submit class: ""%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<h1><%= post.title %></h1>
<br/>
<h4><%= post.post_body %></h4>
<br/>
<h5><%= post.source %></h5>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p class="title">
    New Articles here
</p>
<p class="subtitle">
    all articles was here
</p>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>Created by:</p>
    <%= post.user.email %>
    <P>Posted on :</P>
    <%= post.created_at.strftime('%B, %d, %Y, %l:%M%P') %>
    <p>
      <%= link_to "Show this posts", post %>
    </p>
    <br/>
  <% end %>

</div>

app/views/posts/new.html.erb
<h1>Add new article</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="columns">
  <div class="column is-two-thirds">
    <%= render @post %>
    <a>
      <% if @post.user == current_user %>
      <%= link_to "Edit this posts", edit_post_path(@post), class: "" %> |
      <%= button_to "Destroy this posts", @post, method: :delete, class: "button is-danger" %>
      <% end %>
    </a>
    <h5>
      <%= link_to "Back to posts", posts_path, class: "" %>
    </h5>
  </div>
<!--  comment here-->
  <div class="column">
    <b>Comments</b>
    <br>
    <% @post.comments.each do |comment|%>
      <%= comment.user.email %>
      <%= comment.created_at.strftime('%B, %d, %Y, %l:%M%P') %>
      <%= comment.comment_body %>
      <% if @post.user == current_user %>
      <%= link_to 'edit comment', edit_comment_path(comment) %>
      <%= link_to 'Delete', destroy_comment_path(comment), class: "is-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>
      <% end %>
      <%#= button_to "destroy", @post, method: :delete %>
      <br>
    <% end %>
    <%= render "comments/form", comment: @comment%>
  </div>
<!--  <div class="column">Auto</div>-->
</div>